### ISSUE TITLE
why no solve my AMC (American Mathemtical Competition) Problems for the upcoming AMC 10 Competiton on November 10, 2021 from 8:00 am ET to 11:59 PM EST

### ISSUE THREAD

**Issue by bobbykabob** [Hudson-1/HudLearnCode#1]
why no solve my AMC (American Mathemtical Competition) Problems for the upcoming AMC 10 Competiton on November 10, 2021 from 8:00 am ET to 11:59 PM EST 
0/10

**Comment by Hudson-1** [comment]
[here is solution](https://www.youtube.com/watch?v=iik25wqIuFo)
